Add example of unit tests
mikro-orm/nestjs-realworld-example-app pull request #34
Opened 2022-01-09 16:59 UTC by VladPetriv

Add unit tests for user controller and service)

2022-01-14 11:37 UTC, B4nan requested changes
please remove those code style changes in `UserService` and keep just the tests

2022-01-14 11:49 UTC, VladPetriv commented
Ok

2022-01-17 10:09 UTC, B4nan approved these changes

2022-01-17 10:09 UTC, merged

2022-01-17 10:09 UTC, B4nan commented
thanks!